-- =====================================================================
-- Watheqa - Official Egyptian Mutual Funds Arabic Localization
-- Updates name_ar and name_en for all 201 EIMA funds
-- =====================================================================

UPDATE public.funds SET name_ar = 'صندوق استثمار بنك كريدي أجريكول مصر الأول (أسهم)', name_en = 'Credit Agricole Egypt Fund I' WHERE name LIKE '%Credit Agricole Egypt Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك الإسكندرية الأول', name_en = 'ALEXBANK Fund I' WHERE name LIKE '%ALEXBANK Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار جي آي جي للتأمين الأول', name_en = 'GIG Insurance - Egypt Fund I' WHERE name LIKE '%GIG Insurance - Egypt Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك مصر الثاني (النمو الرأسمالي)', name_en = 'Banque Misr Fund II' WHERE name LIKE '%Banque Misr Fund II%';
UPDATE public.funds SET name_ar = 'صندوق استثمار البنك الأهلي المصري الثاني (أسهم)', name_en = 'National Bank of Egypt Fund II' WHERE name LIKE '%National Bank of Egypt Fund II%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك القاهرة الأول (الأسهم)', name_en = 'Banque Du Caire Fund I' WHERE name LIKE '%Banque Du Caire Fund I%';
UPDATE public.funds SET name_ar = 'صندوق بنك تنمية الصادرات (الخبير)', name_en = 'Ebank Fund (El Khabeer)' WHERE name LIKE '%Ebank Fund (El Khabeer)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك قناة السويس الأول', name_en = 'Suez Canal Bank Fund I' WHERE name LIKE '%Suez Canal Bank Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك كريدي أجريكول مصر الثاني', name_en = 'Credit Agricole Egypt Fund II' WHERE name LIKE '%Credit Agricole Egypt Fund II%';
UPDATE public.funds SET name_ar = 'صندوق البنك المصري الخليجي الأول', name_en = 'Egyptian Gulf Bank Fund I' WHERE name LIKE '%Egyptian Gulf Bank Fund I%';
UPDATE public.funds SET name_ar = 'صندوق البنك العربي الأفريقي الدولي (شيلد للأسهم)', name_en = 'Arab African International Bank (Shield)' WHERE name LIKE '%Arab African International Bank (Shield)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك مصر الثالث (عائد تراكمي وتوزيع دوري)', name_en = 'Banque Misr Fund III' WHERE name LIKE '%Banque Misr Fund III%';
UPDATE public.funds SET name_ar = 'صندوق استثمار ميد بنك الأول (أسهم)', name_en = 'MID Bank Fund I' WHERE name LIKE '%MID Bank Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار البنك الأهلي المصري الثالث', name_en = 'National Bank of Egypt Fund III' WHERE name LIKE '%National Bank of Egypt Fund III%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك CIB الثاني (استثمار)', name_en = 'CIB Fund II (Istthmar)' WHERE name LIKE '%CIB Fund II (Istthmar)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار البنك الأهلي المصري الخامس', name_en = 'National Bank of Egypt Fund V' WHERE name LIKE '%National Bank of Egypt Fund V%';
UPDATE public.funds SET name_ar = 'صندوق استثمار البنك الأهلي الكويتي - مصر الأول', name_en = 'Al Ahli Bank of Kuwait - Egypt Fund I' WHERE name LIKE '%Al Ahli Bank of Kuwait - Egypt Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك التعمير والإسكان (التعمير)', name_en = 'Housing & Development Bank ( AL Tameer)' WHERE name LIKE '%Housing & Development Bank ( AL Tameer)%';
UPDATE public.funds SET name_ar = 'صندوق بنك المؤسسة العربية المصرفية ABC الأول', name_en = 'Bank ABC Fund I' WHERE name LIKE '%Bank ABC Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك قناة السويس الثاني (الأجيال)', name_en = 'Suez Canal Bank Fund II (Al Agial)' WHERE name LIKE '%Suez Canal Bank Fund II (Al Agial)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك بلوم مصر الأول', name_en = 'Blom Bank Fund I' WHERE name LIKE '%Blom Bank Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار فاروس الأول للأسهم', name_en = 'Pharos Fund I' WHERE name LIKE '%Pharos Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بايونيرز الأول (الرائد)', name_en = 'Pioneers Fund I' WHERE name LIKE '%Pioneers Fund I%';
UPDATE public.funds SET name_ar = 'صندوق استثمار مصر المستقبل', name_en = 'Misr Al Mostakbal Fund' WHERE name LIKE '%Misr Al Mostakbal Fund%';
UPDATE public.funds SET name_ar = 'صندوق بنك الكويت الوطني (نماء للأسهم)', name_en = 'National Bank of Kuwait Fund (Namaa)' WHERE name LIKE '%National Bank of Kuwait Fund (Namaa)%';
UPDATE public.funds SET name_ar = 'صندوق أزيموت لفرص الأسهم (AZ Foras)', name_en = 'AZ Foras' WHERE name LIKE '%AZ Foras%';
UPDATE public.funds SET name_ar = 'صندوق مباشر لأسهم البورصة المصرية', name_en = 'Mubasher Equity' WHERE name LIKE '%Mubasher Equity%';
UPDATE public.funds SET name_ar = 'صندوق كنز لفرص الأسهم المصرية', name_en = 'Kenz Foras Equity' WHERE name LIKE '%Kenz Foras Equity%';
UPDATE public.funds SET name_ar = 'صندوق معاشي للتقاعد والاستثمار', name_en = 'Maashy' WHERE name LIKE '%Maashy%';
UPDATE public.funds SET name_ar = 'صندوق مومينتم للنمو الرأسمالي', name_en = 'Momentum' WHERE name LIKE '%Momentum%';
UPDATE public.funds SET name_ar = 'صندوق أودن ترند ألفا للأسهم', name_en = 'Odin Trend Alpha' WHERE name LIKE '%Odin Trend Alpha%';
UPDATE public.funds SET name_ar = 'صندوق بلتون ألفا (B-Alpha)', name_en = 'B-Alpha' WHERE name LIKE '%B-Alpha%';
UPDATE public.funds SET name_ar = 'صندوق هيرميس للأسهم المصرية', name_en = 'Hermes Equity' WHERE name LIKE '%Hermes Equity%';
UPDATE public.funds SET name_ar = 'صندوق جسور للأسهم', name_en = 'Gosour Equity' WHERE name LIKE '%Gosour Equity%';
UPDATE public.funds SET name_ar = 'صندوق زالدي المصري للاستثمار', name_en = 'Zaldi El Masry' WHERE name LIKE '%Zaldi El Masry%';
UPDATE public.funds SET name_ar = 'صندوق أسباير وفرة بلس', name_en = 'Aspire Waffrah Plus' WHERE name LIKE '%Aspire Waffrah Plus%';
UPDATE public.funds SET name_ar = 'صندوق بنك قطر الوطني الأهلي (تداول للأسهم)', name_en = 'QNB AlAHLI (Tadawol)' WHERE name LIKE '%QNB AlAHLI (Tadawol)%';
UPDATE public.funds SET name_ar = 'صندوق بنك فيصل الإسلامي المصري', name_en = 'Faisal Islamic Bank of Egypt Fund' WHERE name LIKE '%Faisal Islamic Bank of Egypt Fund%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك البركة مصر (ذو العائد الدوري)', name_en = 'Al Baraka Bank Egypt' WHERE name LIKE '%Al Baraka Bank Egypt%';
UPDATE public.funds SET name_ar = 'صندوق أمان الإسلامي (بنك فيصل و CIB)', name_en = 'FIBE & CIB (Aman)' WHERE name LIKE '%FIBE & CIB (Aman)%';
UPDATE public.funds SET name_ar = 'صندوق بنك مصر الرابع (الحصن المتوافق مع الشريعة)', name_en = 'Banque Misr Fund IV' WHERE name LIKE '%Banque Misr Fund IV%';
UPDATE public.funds SET name_ar = 'صندوق سنابل الإسلامي (SAIB ومصرف أبوظبي الإسلامي)', name_en = 'SAIB & ADIB Fund (Sanabel)' WHERE name LIKE '%SAIB & ADIB Fund (Sanabel)%';
UPDATE public.funds SET name_ar = 'صندوق بشائر الإسلامي (البنك الأهلي وبنك البركة)', name_en = 'NBE & Al Baraka Bank Egypt Fund (Bashayer)' WHERE name LIKE '%NBE & Al Baraka Bank Egypt Fund (Bashayer)%';
UPDATE public.funds SET name_ar = 'صندوق بنك الكويت الوطني (الحياة الإسلامي)', name_en = 'National Bank of Kuwait (Hayat)' WHERE name LIKE '%National Bank of Kuwait (Hayat)%';
UPDATE public.funds SET name_ar = 'صندوق بنك نكست الثاني (هلال المتوافق مع الشريعة)', name_en = 'Bank Nxt Fund II (Helal)' WHERE name LIKE '%Bank Nxt Fund II (Helal)%';
UPDATE public.funds SET name_ar = 'صندوق نعيم مصر الاستثماري المتوافق مع الشريعة', name_en = 'Naeem Misr Fund' WHERE name LIKE '%Naeem Misr Fund%';
UPDATE public.funds SET name_ar = 'صندوق الوفاق الإسلامي (البنك الزراعي وبنك القاهرة)', name_en = 'Agriculural Bank of Egypt (Al Wefak)' WHERE name LIKE '%Agriculural Bank of Egypt (Al Wefak)%';
UPDATE public.funds SET name_ar = 'صندوق أزيموت لفرص الشريعة (AZ-Foras Shariah)', name_en = 'AZ-Foras Shariah' WHERE name LIKE '%AZ-Foras Shariah%';
UPDATE public.funds SET name_ar = 'صندوق هيرميس للشريعة الإسلامية', name_en = 'Hermes Shariah' WHERE name LIKE '%Hermes Shariah%';
UPDATE public.funds SET name_ar = 'صندوق بيت التمويل الكويتي ألفا (KFH Alpha)', name_en = 'KFH Bank (Alpha)' WHERE name LIKE '%KFH Bank (Alpha)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك كريدي أجريكول مصر الثالث (النقدي)', name_en = 'Credit Agricole Egypt Fund III' WHERE name LIKE '%Credit Agricole Egypt Fund III%';
UPDATE public.funds SET name_ar = 'صندوق مصر للتأمين النقدي اليومي', name_en = 'Misr Money Market' WHERE name LIKE '%Misr Money Market%';
UPDATE public.funds SET name_ar = 'صندوق استثمار CIB الأول (أصول اليومي التراكمي)', name_en = 'CIB Fund I (Osoul)' WHERE name LIKE '%CIB Fund I (Osoul)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار ميد بنك الثاني (النقدي اليومي)', name_en = 'MID Bank Fund II' WHERE name LIKE '%MID Bank Fund II%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك الإسكندرية الثاني (عائد يومي تراكمي)', name_en = 'ALEXBANK Fund II' WHERE name LIKE '%ALEXBANK Fund II%';
UPDATE public.funds SET name_ar = 'صندوق استثمار البنك الأهلي المصري الرابع (اليومي التراكمي)', name_en = 'National Bank of Egypt Fund IV' WHERE name LIKE '%National Bank of Egypt Fund IV%';
UPDATE public.funds SET name_ar = 'صندوق ثمار بنك QNB الأهلي (النقدي اليومي التراكمي)', name_en = 'QNB AlAhli (Themar)' WHERE name LIKE '%QNB AlAhli (Themar)%';
UPDATE public.funds SET name_ar = 'صندوق البنك المصري لتنمية الصادرات الثاني (النقدي)', name_en = 'Ebank Fund II' WHERE name LIKE '%Ebank Fund II%';
UPDATE public.funds SET name_ar = 'صندوق بنك ABC (مزايا النقدي)', name_en = 'Bank ABC Fund (Mazaya)' WHERE name LIKE '%Bank ABC Fund (Mazaya)%';
UPDATE public.funds SET name_ar = 'صندوق بنك HSBC مصر النقدي', name_en = 'HSBC Egypt Bank Fund' WHERE name LIKE '%HSBC Egypt Bank Fund%';
UPDATE public.funds SET name_ar = 'صندوق البنك العربي الأفريقي الدولي (جمان النقدي اليومي)', name_en = 'Arab African International Bank (Juman)' WHERE name LIKE '%Arab African International Bank (Juman)%';
UPDATE public.funds SET name_ar = 'صندوق البنك الأهلي الكويتي - مصر الثاني (النقدي)', name_en = 'Al Ahli Bank of Kuwait - Egypt Fund II' WHERE name LIKE '%Al Ahli Bank of Kuwait - Egypt Fund II%';
UPDATE public.funds SET name_ar = 'صندوق بنك أبوظبي الأول مصر (مدخراتي النقدي)', name_en = 'FAB Misr (Modkharaty)' WHERE name LIKE '%FAB Misr (Modkharaty)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك القاهرة الثاني (النقدي اليومي)', name_en = 'Banque Du Caire Fund II' WHERE name LIKE '%Banque Du Caire Fund II%';
UPDATE public.funds SET name_ar = 'صندوق استثمار بنك بلوم مصر الثاني (النقدي)', name_en = 'Blom Bank Fund II' WHERE name LIKE '%Blom Bank Fund II%';
UPDATE public.funds SET name_ar = 'صندوق بنك الكويت الوطني (إشراق النقدي اليومي)', name_en = 'National Bank of Kuwait Fund (Ishraq)' WHERE name LIKE '%National Bank of Kuwait Fund (Ishraq)%';
UPDATE public.funds SET name_ar = 'صندوق البنك العربي (يوماتي النقدي اليومي)', name_en = 'Arab Bank Fund (Yomaty)' WHERE name LIKE '%Arab Bank Fund (Yomaty)%';
UPDATE public.funds SET name_ar = 'صندوق بنك التعمير والإسكان (موارد النقدي)', name_en = 'Housing & Development Bank (Mawared)' WHERE name LIKE '%Housing & Development Bank (Mawared)%';
UPDATE public.funds SET name_ar = 'صندوق البنك الزراعي المصري (الحصاد اليومي)', name_en = 'Agricultural Bank of Egypt (Al Hasad Al Yaumy)' WHERE name LIKE '%Agricultural Bank of Egypt (Al Hasad Al Yaumy)%';
UPDATE public.funds SET name_ar = 'صندوق بنك نكست الأول (النقدي اليومي)', name_en = 'Bank Nxt Fund I' WHERE name LIKE '%Bank Nxt Fund I%';
UPDATE public.funds SET name_ar = 'صندوق البنك المصري الخليجي (ثراء النقدي)', name_en = 'Egyptian Gulf Bank (Tharaa)' WHERE name LIKE '%Egyptian Gulf Bank (Tharaa)%';
UPDATE public.funds SET name_ar = 'صندوق بنك أبوظبي الأول (الأول النقدي)', name_en = 'Fab Misr (Al Awal)' WHERE name LIKE '%Fab Misr (Al Awal)%';
UPDATE public.funds SET name_ar = 'صندوق بنك SAIB (اليومي النقدي)', name_en = 'Saib (Yaumy Fund)' WHERE name LIKE '%Saib (Yaumy Fund)%';
UPDATE public.funds SET name_ar = 'صندوق استثمار مصر للتأمين النقدي', name_en = 'Misr Insurance Fund' WHERE name LIKE '%Misr Insurance Fund%';
UPDATE public.funds SET name_ar = 'صندوق التجاري وفا بنك النقدي', name_en = 'Attijariwafa BankFund' WHERE name LIKE '%Attijariwafa BankFund%';
UPDATE public.funds SET name_ar = 'صندوق بنك الإمارات دبي الوطني (مزيد النقدي)', name_en = 'Emirates NBD (Mazid)' WHERE name LIKE '%Emirates NBD (Mazid)%';
UPDATE public.funds SET name_ar = 'صندوق بنك قناة السويس (السويس اليومي)', name_en = 'Suez Canal Bank ( Al Suez Al Youmi)' WHERE name LIKE '%Suez Canal Bank ( Al Suez Al Youmi)%';
UPDATE public.funds SET name_ar = 'صندوق سيولة للأسواق النقدية (إن أي كابيتال)', name_en = 'Siula Money Market' WHERE name LIKE '%Siula Money Market%';
UPDATE public.funds SET name_ar = 'صندوق مصر لتأمينات الحياة النقدي', name_en = 'Misr Life Insurance Fund' WHERE name LIKE '%Misr Life Insurance Fund%';
UPDATE public.funds SET name_ar = 'صندوق وثاق للتأمين التكافلي النقدي', name_en = 'Wethaq' WHERE name LIKE '%Wethaq%';
UPDATE public.funds SET name_ar = 'صندوق فوري اليومي التراكمي (سند إسلامي)', name_en = 'Fawry' WHERE name LIKE '%Fawry%';
UPDATE public.funds SET name_ar = 'صندوق أمان للتمويل متناهي الصغر النقدي', name_en = 'Aman Micro Finance' WHERE name LIKE '%Aman Micro Finance%';
UPDATE public.funds SET name_ar = 'صندوق أزيموت جولد للاستثمار في الذهب (AZ-Gold)', name_en = 'AZ-Gold' WHERE name LIKE '%AZ-Gold%' OR name LIKE '%az-gold%';
UPDATE public.funds SET name_ar = 'صندوق الأهلي دهب للاستثمار في سبائك الذهب', name_en = 'Al Ahly Dahab' WHERE name LIKE '%Ahly Dahab%' OR name LIKE '%الأهلي دهب%';
UPDATE public.funds SET name_ar = 'صندوق بلتون سبائك للاستثمار في الذهب عيار 24', name_en = 'Beltone Sabayek Gold' WHERE name LIKE '%Sabayek%' OR name LIKE '%سبائك%';

-- For any fund that still has name_ar as English, fall back to proper naming
UPDATE public.funds SET name_ar = name WHERE name_ar IS NULL OR name_ar = '';
